aks pipeline

diff --git a/.github/actions/deploy-environment-aks/action.yml b/.github/actions/deploy-environment-aks/action.yml
--- a/.github/actions/deploy-environment-aks/action.yml
+++ b/.github/actions/deploy-environment-aks/action.yml
@@ -45,12 +45,12 @@ runs:
       shell: bash
       id: set_outputs
       run: |
-        environment_url=$(terraform -chdir=terraform/application output -json url | jq -r '.[0]')
-        echo "ENVIRONMENT_URL=$environment_url" >> $GITHUB_OUTPUT
+        source <(terraform output --json | jq -r 'keys[] as $k | "\($k|ascii_upcase)=\(.[$k] | .value)"')
+        echo "ENVIRONMENT_URL=$URL" >> $GITHUB_OUTPUT
 
     - name: Run smoke tests
       shell: bash
       run: |
-        environment_url=$(terraform -chdir=terraform/application output -json url | jq -r '.[0]')
-        echo "Check health for $environment_url/health/all.json..."
-        curl -sS --fail "$environment_url/health/all.json" > /dev/null && echo "Health check passed for $url" || echo "Health check failed for $url"
+        source <(terraform output --json | jq -r 'keys[] as $k | "\($k|ascii_upcase)=\(.[$k] | .value)"')
+        echo "Check health for $URL/health/all.json..."
+        curl -sS --fail "$URL/health/all.json" > /dev/null && echo "Health check passed for $URL" || echo "Health check failed for $URL"
